"""Add HTTPX fields to subdomains

Revision ID: 11e45cc8193d
Revises: 37c147a2c856
Create Date: 2026-06-29 20:34:43.457029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11e45cc8193d'
down_revision: Union[str, Sequence[str], None] = '37c147a2c856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subdomains', sa.Column('status_code', sa.Integer(), nullable=True))
    op.add_column('subdomains', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('subdomains', sa.Column('scheme', sa.String(length=10), nullable=True))
    op.add_column('subdomains', sa.Column('ip', sa.String(length=50), nullable=True))
    op.add_column('subdomains', sa.Column('webserver', sa.String(length=100), nullable=True))
    op.add_column('subdomains', sa.Column('technologies', sa.Text(), nullable=True))
    op.add_column('subdomains', sa.Column('content_length', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subdomains', 'content_length')
    op.drop_column('subdomains', 'technologies')
    op.drop_column('subdomains', 'webserver')
    op.drop_column('subdomains', 'ip')
    op.drop_column('subdomains', 'scheme')
    op.drop_column('subdomains', 'title')
    op.drop_column('subdomains', 'status_code')
    # ### end Alembic commands ###
